<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{e36a512e-fa25-440c-ad65-a91fa6a1270d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//*************************************************************
// Chain of Responsibility
//*************************************************************
	PRG_SampleChainOfResponsibility();

//*************************************************************
// Command Pattern 
//*************************************************************
	PRG_SampleCommandPattern();
	
//*************************************************************
// Iterator Pattern 
//*************************************************************
	PRG_SampleIterator();

//*************************************************************
// Mediator Pattern 
//*************************************************************
	PRG_SampleMediator();
	
//*************************************************************
// Memento Pattern 
//*************************************************************
	PRG_SampleMemento();		

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>