<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CmdLightOff" Id="{24e68c8e-25d3-4997-98ae-e7c2f4df045b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CmdLightOff IMPLEMENTS I_Command
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_ipLight				: I_Light;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="execute" Id="{19e333ec-461d-4314-b376-e7fa715a20cc}">
      <Declaration><![CDATA[METHOD execute : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ipLight.turnLightOff();]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{0d49fddc-1181-4092-83ee-69feb0212b5f}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)   
	ipLight: I_Light;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ipLight := ipLight;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>